
# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a data set which contains information World cup matches. Let's use the pandas commands learned in the previous lecture to learn more about our data!

## Objectives
You will be able to:
* Understand and explain some key Pandas methods
* Access DataFrame data by using the label
* Perform boolean indexing on both Series and DataFrames
* Use simple selectors for series
* Set new Series and DataFrame inputs

## Load the data

Load the file `WorldCupMatches.csv` as a dataframe in Pandas

In [63]:
import pandas as pd
df = pd.read_csv('WorldCupMatches.csv')

## Common methods and attributes

Use the correct method to look at the first 7 rows of the data set.

In [2]:
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
5,1930.0,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3.0,0.0,Mexico,,9249.0,1.0,0.0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201.0,1095.0,CHI,MEX
6,1930.0,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4.0,0.0,Bolivia,,18306.0,0.0,0.0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201.0,1092.0,YUG,BOL

Look at the last 3 rows of the data set.

In [3]:
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get a concise summary of your data using `.info()`

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
Year                    852 non-null float64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null float64
Away Team Goals         852 non-null float64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null float64
Half-time Away Goals    852 non-null float64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null float64
MatchID                 852 non-null float64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(8), object(12)
memory usage: 714.5+ KB

Obtain a tuple representing the number of rows and number of columns

In [5]:
df.shape

(4572, 20)

Use the appropriate attribute to get the column names

In [7]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting dataframe information

When looking at the dataframe's `.head()`, you might have noticed that the games are structured chronologically in the dataframe.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [9]:
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
5,1930.0,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3.0,0.0,Mexico,,9249.0,1.0,0.0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201.0,1095.0,CHI,MEX

Now, print all the info from game 5-9, but we're only interested to print out the "Home Team Name" and the "Away Team Name",

In [17]:
df.loc[5:10,['Home Team Name','Away Team Name']]

   Home Team Name Away Team Name
5           Chile         Mexico
6      Yugoslavia        Bolivia
7             USA       Paraguay
8         Uruguay           Peru
9           Chile         France
10      Argentina         Mexico

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [26]:
df.loc[(df['Year']== 1950) & (df['Stage']=='Group 3')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
56,1950.0,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3.0,2.0,Italy,,36502.0,2.0,1.0,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208.0,1219.0,SWE,ITA
61,1950.0,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2.0,2.0,Paraguay,,7903.0,2.0,1.0,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208.0,1228.0,SWE,PAR
65,1950.0,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2.0,0.0,Paraguay,,25811.0,1.0,0.0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208.0,1218.0,ITA,PAR

Let's repeat the command above, but now we only want to print out the attendance colum for the Group 3 games

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [29]:
df.loc[(df['Stage']=='Group 3') & (df['Year'] == 1950), 'Attendance']

56    36502.0
61     7903.0
65    25811.0
Name: Attendance, dtype: float64

Throughout the entire history of the world cup, How many Home games were played by the Netherlands?

In [32]:
len(df.loc[(df['Home Team Name']=='Netherlands')])

32

How many games were playes by the Netherlands in total?

In [33]:
len(df.loc[(df['Home Team Name']=='Netherlands') | (df['Away Team Name']=='Netherlands')])

54

Next, let's try and figure out how many games the USA played in the 2014 world cup.

In [44]:
USA_home_away = df.loc[(df['Year']==2014) & ((df['Home Team Name']=='USA') | (df['Away Team Name']=='USA'))]
USA_home_away.head()
len(USA_home_away)

5

Now, let's try to find out how many countries participated in the 1986 world cup.

Hint 1: as a first step, create a new data set that only contain games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [46]:
Year_1986 = df.loc[df['Year']==1986]
Year_1986.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
360,1986.0,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,96000.0,0.0,1.0,FREDRIKSSON Erik (SWE),CODESAL MENDEZ Edgardo (MEX),ROTH Volker (GER),308.0,459.0,BUL,ITA
361,1986.0,01 Jun 1986 - 16:00,Group C,Nou Camp - Estadio Le�n,Leon,Canada,0.0,1.0,France,,65500.0,0.0,0.0,SILVA ARCE Hernan (CHI),MENDEZ MOLINA Romulo (GUA),ULLOA MORERA Berny (CRC),308.0,468.0,CAN,FRA
362,1986.0,01 Jun 1986 - 12:00,Group D,Jalisco,Guadalajara,Spain,0.0,1.0,Brazil,,35748.0,0.0,0.0,BAMBRIDGE Christopher (AUS),SOCHA David (USA),KEIZER Jan (NED),308.0,439.0,ESP,BRA
363,1986.0,02 Jun 1986 - 12:00,Group C,Estadio Irapuato,Irapuato,Soviet Union,6.0,0.0,Hungary,,16500.0,3.0,0.0,AGNOLIN Luigi (ITA),COURTNEY George (ENG),BRUMMEIER Horst (AUT),308.0,610.0,URS,HUN
364,1986.0,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3.0,1.0,Korea Republic,,60000.0,2.0,0.0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308.0,395.0,ARG,KOR

In [52]:
home_86 = list(Year_1986['Home Team Name'].unique())
away_86 = list(Year_1986['Away Team Name'].unique())
print(len(home_86))
print(len(away_86))
print(len(home_86) + len(away_86))

24
24
48

In the world cup history, how matches had more than 5 goals in total?

In [56]:
five_goals = df.loc[(df['Home Team Goals'] + df['Away Team Goals'])>=5]
len(five_goals)

147

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column "Half-time Goals".

In [59]:
df['Half-time Goals'] = df['Half-time Home Goals'] + df['Half-time Away Goals']
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Half-time Goals
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,...,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX,3.0
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,...,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL,2.0
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,...,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA,2.0
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,...,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER,1.0
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,...,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA,0.0

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [64]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

ValueError: cannot index with vector containing NA / NaN values

Imagine that for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [68]:
df.loc[df['Home Team Name']== 'Korea DPR', 'Home Team Name'] = 'Korea'
df.loc[df['Home Team Name']== 'Korea Republic', 'Home Team Name'] = "Korea"
df.loc[df['Away Team Name']== 'Korea Republic', 'Away Team Name'] = "Korea"
df.loc[df['Away Team Name']== 'Korea DPR', 'Away Team Name'] = "Korea"
df.loc[df['Home Team Initials']== 'KOR', 'Home Team Initials'] = "NSK"
df.loc[df['Home Team Initials']== 'PRK', 'Home Team Initials'] = "NSK"
df.loc[df['Away Team Initials']== 'KOR', 'Away Team Initials'] = "NSK"
df.loc[df['Away Team Initials']== 'PRK', 'Away Team Initials'] = "NSK"

Make sure to verify your answer!

In [71]:
df.loc[df['Home Team Name']=='Korea']

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
179,1966.0,15 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1.0,1.0,Chile,,13792.0,0.0,1.0,KANDIL Aly Hussein (EGY),CRAWFORD William (SCO),FINNEY Jim (ENG),238.0,1609.0,NSK,CHI
187,1966.0,19 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1.0,0.0,Italy,,17829.0,1.0,0.0,SCHWINTE Pierre (FRA),ADAIR John (NIR),TAYLOR John (ENG),238.0,1679.0,NSK,ITA
374,1986.0,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1.0,1.0,Bulgaria,,45000.0,0.0,1.0,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308.0,460.0,NSK,BUL
386,1986.0,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2.0,3.0,Italy,,20000.0,0.0,1.0,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308.0,643.0,NSK,ITA
434,1990.0,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1.0,3.0,Spain,,32733.0,1.0,1.0,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322.0,175.0,NSK,ESP
444,1990.0,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0.0,1.0,Uruguay,,29039.0,0.0,0.0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322.0,290.0,NSK,URU
480,1994.0,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0.0,0.0,Bolivia,,54453.0,0.0,0.0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337.0,3065.0,NSK,BOL
524,1998.0,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1.0,3.0,Mexico,,39100.0,1.0,0.0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014.0,8732.0,NSK,MEX
593,2002.0,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2.0,0.0,Poland,,48760.0,1.0,0.0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100.0,43950014.0,NSK,POL
609,2002.0,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1.0,1.0,USA,,60778.0,0.0,1.0,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100.0,43950030.0,NSK,USA
635,2002.0,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2.0,1.0,Italy,Win on Golden Goal,38588.0,0.0,0.0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200.0,43950056.0,NSK,ITA
642,2002.0,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2.0,3.0,Turkey,,63483.0,1.0,3.0,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500.0,43950063.0,NSK,TUR
655,2006.0,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2.0,1.0,Togo,,48000.0,0.0,1.0,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100.0,97410014.0,NSK,TOG
710,2010.0,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2.0,0.0,Greece,,31513.0,1.0,0.0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722.0,300061459.0,NSK,GRE
753,2010.0,25 Jun 2010 - 16:00,Group G,Mbombela Stadium,Nelspruit,Korea,0.0,3.0,C�te d'Ivoire,,34763.0,0.0,2.0,Alberto UNDIANO MALLENCO (ESP),MARTINEZ Fermin (ESP),YUSTE Juan (ESP),249722.0,300061486.0,NSK,CIV
802,2014.0,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2.0,4.0,Algeria,,42732.0,0.0,3.0,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931.0,300186495.0,NSK,ALG
818,2014.0,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0.0,1.0,Belgium,,61397.0,0.0,0.0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931.0,300186480.0,NSK,BEL